# Start with the official Kali Linux base image
FROM kalilinux/kali-rolling:latest

# Install necessary packages
RUN apt-get update && \
    apt-get install -y \
        python3 \
        python3-pip
        # curl \
        # # Add any pentesting tools you want
        # nmap \
        # assetfinder \
        # && apt-get clean

# Install MCP server dependencies
RUN pip3 install mcp

# Copy your MCP server code into the container
WORKDIR /app
COPY tools ./tools
COPY mcpserver.py .

# Expose HTTP port
EXPOSE 8000

# Start MCP server
CMD ["python3", "mcpserver.py", "info_gathering"]