[project]
name = "secagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anthropic>=0.66.0",
    "mcp>=1.13.1",
    "nest-asyncio>=1.6.0",
    "pyfiglet>=1.0.4",
]
